version: '3.1'
services:
  seed:
    image: akka-events-booking-java:1.0-SNAPSHOT
    ports:
      - '2551:2551'
      - '8080:8080'
    environment:
      CLUSTER_PORT: 2551
      CLUSTER_IP: seed
      SEED_PORT_2551_TCP_ADDR: seed
      HTTP_PORT: 8080
  c1:
    image: akka-events-booking-java:1.0-SNAPSHOT
    ports:
      - '2552:2552'
      - '8081:8081'
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: c1
      SEED_PORT_2551_TCP_ADDR: seed
      HTTP_PORT: 8081
  c2:
    image: akka-events-booking-java:1.0-SNAPSHOT
    ports:
      - '2553:2553'
      - '8082:8082'
    environment:
      CLUSTER_PORT: 2553
      CLUSTER_IP: c2
      SEED_PORT_2551_TCP_ADDR: seed
      HTTP_PORT: 8082


